//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyWheelsSales.WebUI.Resources.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetProfile_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetProfile_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedyWheelsSales.WebUI.Resources.Views.Profile.GetProfile.uk", typeof(GetProfile_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архівовані оголошення.
        /// </summary>
        internal static string Archived_Ads {
            get {
                return ResourceManager.GetString("Archived Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити фото.
        /// </summary>
        internal static string Change_photo {
            get {
                return ResourceManager.GetString("Change photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нове оголошення.
        /// </summary>
        internal static string Create_new_ad {
            get {
                return ResourceManager.GetString("Create new ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИДАЛЕНЕ.
        /// </summary>
        internal static string DELETED {
            get {
                return ResourceManager.GetString("DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати профіль.
        /// </summary>
        internal static string Edit_profile {
            get {
                return ResourceManager.GetString("Edit profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помітити проданим.
        /// </summary>
        internal static string Mark_as_sold {
            get {
                return ResourceManager.GetString("Mark as sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активних оголошень не знайдено.
        /// </summary>
        internal static string No_active_ads_found {
            get {
                return ResourceManager.GetString("No active ads found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архівованих оголошень не знайдено.
        /// </summary>
        internal static string No_archived_ads_found {
            get {
                return ResourceManager.GetString("No archived ads found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити чат.
        /// </summary>
        internal static string Open_chat {
            get {
                return ResourceManager.GetString("Open chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to профіль.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєстрований.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОДАНО.
        /// </summary>
        internal static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
    }
}
