//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyWheelsSales.WebUI.Resources.Views.SavedSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetSavedSearches_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetSavedSearches_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedyWheelsSales.WebUI.Resources.Views.SavedSearch.GetSavedSearches.en", typeof(GetSavedSearches_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine type.
        /// </summary>
        internal static string EngineType {
            get {
                return ResourceManager.GetString("EngineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ads.
        /// </summary>
        internal static string Go_to_ads {
            get {
                return ResourceManager.GetString("Go to ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max engine size.
        /// </summary>
        internal static string MaxEngineSize {
            get {
                return ResourceManager.GetString("MaxEngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max fuel consumption.
        /// </summary>
        internal static string MaxFuelConsumption {
            get {
                return ResourceManager.GetString("MaxFuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max manufacture year.
        /// </summary>
        internal static string MaxManufactureYear {
            get {
                return ResourceManager.GetString("MaxManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max mileage.
        /// </summary>
        internal static string MaxMileage {
            get {
                return ResourceManager.GetString("MaxMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max price.
        /// </summary>
        internal static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min engine size.
        /// </summary>
        internal static string MinEngineSize {
            get {
                return ResourceManager.GetString("MinEngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min manufacture year.
        /// </summary>
        internal static string MinManufactureYear {
            get {
                return ResourceManager.GetString("MinManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min price.
        /// </summary>
        internal static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved searches found.
        /// </summary>
        internal static string No_saved_searches_found {
            get {
                return ResourceManager.GetString("No saved searches found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Search.
        /// </summary>
        internal static string Saved_Search {
            get {
                return ResourceManager.GetString("Saved Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved searches.
        /// </summary>
        internal static string Saved_searches {
            get {
                return ResourceManager.GetString("Saved searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of drive.
        /// </summary>
        internal static string TypeOfDrive {
            get {
                return ResourceManager.GetString("TypeOfDrive", resourceCulture);
            }
        }
    }
}
