//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyWheelsSales.WebUI.Resources.Views.Ad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetCreateAdView_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetCreateAdView_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedyWheelsSales.WebUI.Resources.Views.Ad.GetCreateAdView.uk", typeof(GetCreateAdView_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренд.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити оголошення.
        /// </summary>
        internal static string Create_ad {
            get {
                return ResourceManager.GetString("Create ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єм двигуна.
        /// </summary>
        internal static string Engine_size {
            get {
                return ResourceManager.GetString("Engine size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип двигуна.
        /// </summary>
        internal static string Engine_type {
            get {
                return ResourceManager.GetString("Engine type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розхід палива.
        /// </summary>
        internal static string Fuel_consumption {
            get {
                return ResourceManager.GetString("Fuel consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне фото(обов&apos;язково).
        /// </summary>
        internal static string Main_photo_required_ {
            get {
                return ResourceManager.GetString("Main photo(required)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата випуску.
        /// </summary>
        internal static string Manufacture_date {
            get {
                return ResourceManager.GetString("Manufacture date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробіг.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Держ. номер.
        /// </summary>
        internal static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансміссія.
        /// </summary>
        internal static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привід.
        /// </summary>
        internal static string Type_of_drive {
            get {
                return ResourceManager.GetString("Type of drive", resourceCulture);
            }
        }
    }
}
