//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyWheelsSales.WebUI.Resources.Views.Ad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListAds_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListAds_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedyWheelsSales.WebUI.Resources.Views.Ad.ListAds.uk", typeof(ListAds_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оголошення.
        /// </summary>
        internal static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Застосувати фільтри.
        /// </summary>
        internal static string Apply_filters {
            get {
                return ResourceManager.GetString("Apply filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За зростанням.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренд.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата створення.
        /// </summary>
        internal static string Creation_date {
            get {
                return ResourceManager.GetString("Creation date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За зменшенням.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діапазон об&apos;єму двигуна.
        /// </summary>
        internal static string Engine_size_range {
            get {
                return ResourceManager.GetString("Engine size range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип двигуна.
        /// </summary>
        internal static string Engine_type {
            get {
                return ResourceManager.GetString("Engine type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтрувати оголошення.
        /// </summary>
        internal static string Filter_ads {
            get {
                return ResourceManager.GetString("Filter ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтрація.
        /// </summary>
        internal static string Filtering {
            get {
                return ResourceManager.GetString("Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата виготовлення.
        /// </summary>
        internal static string Manufacture_date {
            get {
                return ResourceManager.GetString("Manufacture date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діапазон дат виготовлення.
        /// </summary>
        internal static string Manufacture_year_range {
            get {
                return ResourceManager.GetString("Manufacture year range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. об&apos;єм двигуна.
        /// </summary>
        internal static string Max_Engine_Size {
            get {
                return ResourceManager.GetString("Max Engine Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. розхід палива.
        /// </summary>
        internal static string Max_fuel_consumption {
            get {
                return ResourceManager.GetString("Max fuel consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. дата виготовлення.
        /// </summary>
        internal static string Max_Manufacture_Year {
            get {
                return ResourceManager.GetString("Max Manufacture Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. пробіг.
        /// </summary>
        internal static string Max_mileage {
            get {
                return ResourceManager.GetString("Max mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. ціна.
        /// </summary>
        internal static string Max_Price {
            get {
                return ResourceManager.GetString("Max Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробіг.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мін. об&apos;єм двигуна.
        /// </summary>
        internal static string Min_Engine_Size {
            get {
                return ResourceManager.GetString("Min Engine Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мін. дата виготовлення.
        /// </summary>
        internal static string Min_Manufacture_Year {
            get {
                return ResourceManager.GetString("Min Manufacture Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мін. ціна.
        /// </summary>
        internal static string Min_Price {
            get {
                return ResourceManager.GetString("Min Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оголошення не знайдені.
        /// </summary>
        internal static string No_ads_found {
            get {
                return ResourceManager.GetString("No ads found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діапазон цін.
        /// </summary>
        internal static string Price_range {
            get {
                return ResourceManager.GetString("Price range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти пошук.
        /// </summary>
        internal static string Save_Search {
            get {
                return ResourceManager.GetString("Save Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОДАНО.
        /// </summary>
        internal static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортувати за.
        /// </summary>
        internal static string Sort_by {
            get {
                return ResourceManager.GetString("Sort by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок сортування.
        /// </summary>
        internal static string Sort_order {
            get {
                return ResourceManager.GetString("Sort order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування.
        /// </summary>
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансміссія.
        /// </summary>
        internal static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привід.
        /// </summary>
        internal static string Type_of_drive {
            get {
                return ResourceManager.GetString("Type of drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше оголошення.
        /// </summary>
        internal static string Your_ad {
            get {
                return ResourceManager.GetString("Your ad", resourceCulture);
            }
        }
    }
}
